name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: SetUp Node.js ${{matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - name: Install dependencies
      run: npm ci
    - name: Test & Cover
      run: npx jest
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: SetUp Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm i typescript
    - name: Build
      run: |
        npm run templates
        npm run pkg-files
        npm run compile
    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      run: |
        cd lib
        semantic-release