name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: SetUp Node.js ${{matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - name: Install dependencies
      run: npm ci
    - name: Test & Cover
      run: npx jest
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: SetUp Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: |
        npm ci
        npm i -g semantic-release
        npm i -g codeclimate-test-reporter
    - name: Test & Cover
      run: npx jest --bail --runInBand
    - name: Build
      run: npm run build --if-present
    - name: CodeClimate
      env:
        CODECLIMATE_REPO_TOKEN: ${{secrets.CODECLIMATE_REPO_TOKEN}}
      run: codeclimate-test-reporter < coverage/lcov.info
    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      run: |
        cd lib
        semantic-release
        find .